# Generated by Django 4.0.5 on 2022-06-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='author',
        ),
    ]
